project:
  type: book
  output-dir: ../docs

engine: knitr

book:
  title: "ggsem: Interactive SEM Visualization and Multi-Group Path Diagrams in R"
  author: "Seung Hyun Min"
  date: today
  repo-url: https://github.com/smin95/ggsem
  chapters:
    - index.qmd

    - part: "Welcome"
      chapters:
        - interactive-sem-r-workflow.qmd
        - ggsem-app-interface-guide.qmd
        - autogenerate_workflow.qmd

    - part: "Code-free SEM Visualization"
      chapters:
        - sem-visualization-basics.qmd
        - sem-parameter-visualization-statistics.qmd
        - sem-multi-group-visualization-gui.qmd

    - part: "Code-free Network Visualization"
      chapters:
        - network-analysis-visualization-r.qmd

    - part: "Single-Group Workflow Using Pre-loaded Objects"
      chapters:
        - import-lavaan-semplot-blavaan-etc-objects.qmd
        - import-igraph-qgraph-etc-objects.qmd

    - part: "Multi-Group SEM Workflow Using Pre-loaded Objects"
      chapters:
        - lavaan-multi-group-sem-visualization.qmd
        - bayesian-multi-group-sem-blavaan.qmd
        - tidysem-multi-group-path-diagrams.qmd
        - openmx-multi-group-sem-plots.qmd

    - part: "Others"
      chapters:
        - aesthetic_grouping.qmd
        - metadata.qmd

    - part: "Appendix"
      chapters:
        - changelog.qmd


#bibliography: references.bib

format:
  html:
    theme:
      light: [dark, "#121212"]
    css: styles.css
    toc: true

website:
  title: "ggsem"
  site-url: https://smin95.github.io/ggsem/
  repo-actions: [edit, issue]
